In [4]:
#NumPy is the core library for numerical computations in Python. We’ll use it to create and manipulate matrices.
import numpy as np

In [5]:
# Create a 3x3 matrix:
matrix_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 3. Perform Matrix Addition:

In [11]:
matrix_2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
matrix_2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [12]:
matrix_sum = matrix_1 + matrix_2
matrix_sum

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

### 4. Matrix multiplication

#### 1. Element wise multiplication

In [8]:
element_wise_product = matrix_1 * matrix_2
element_wise_product

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

#### 2. Matrix multiplication (dot product)

In [9]:
dot_product = matrix_1 @ matrix_2 # mat1 1st row * mat2 1st col, mat2 1st row * mat
dot_product

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [10]:
dot_prod = np.dot(matrix_1, matrix_2)
dot_prod

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])