In [4]:
#NumPy is the core library for numerical computations in Python. We’ll use it to create and manipulate matrices.
import numpy as np

In [5]:
# Create a 3x3 matrix:
matrix_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 3. Perform Matrix Addition:

In [11]:
matrix_2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
matrix_2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [12]:
matrix_sum = matrix_1 + matrix_2
matrix_sum

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

### 4. Matrix multiplication

#### 1. Element wise multiplication

In [8]:
element_wise_product = matrix_1 * matrix_2
element_wise_product

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

#### 2. Matrix multiplication (dot product)

In [9]:
dot_product = matrix_1 @ matrix_2 # mat1 1st row * mat2 1st col, mat1 1st row * mat2 2nd col ....
dot_product

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [10]:
dot_prod = np.dot(matrix_1, matrix_2)
dot_prod

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

### 5. Matrix Transpose

Transpose matrix_1 using both .T and np.transpose():


In [14]:
transpose_1 = matrix_1.T
transpose_2 = np.transpose(matrix_2)
print(transpose_1)
print(transpose_2)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[9 6 3]
 [8 5 2]
 [7 4 1]]


In [15]:
m1 = np.array([[1,4,1],[2,5,2],[3,6,3]])
m2 = np.array([[1,1,1], [2,1,1], [3,1,2]])
m1@m2

array([[12,  6,  7],
       [18,  9, 11],
       [24, 12, 15]])

In [16]:
m1.T

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

### 6. Matrix Inversion

In [18]:
mat_2x2 = np.array([[1, 3], [2, 4]])
inv_mat_2x2 = np.linalg.inv(mat_2x2) # Ainv = adjA/|A| = Transpose of cofactor matrix / |A|
inv_mat_2x2

array([[-2. ,  1.5],
       [ 1. , -0.5]])

In [19]:
mat_3x3 = np.array([[1,2,3], [0,1,4], [5,6,0]])
inv_mat_3x3 = np.linalg.inv(mat_3x3)
inv_mat_3x3

array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

### 7. Determinant of a matrix

In [20]:
det_mat_3x3 = np.linalg.det(mat_3x3)
det_mat_3x3

np.float64(0.9999999999999964)